### ISSUE TITLE
Impressum Link funktioniert nicht...

### ISSUE THREAD

**Issue by mozzbozz** [locator-kn/locator-app#3]
Der Link ganz unten führt nur zu `http://locator-app.com/#` und die Seite scrollt wieder nach ganz oben...

**Comment by timoweiss** [comment]
liegt evtl. daran, dass es keines gibt?! :smile:  @mozzbozz

**Comment by mozzbozz** [comment]
Naja, ihr habt's ja [zumindest halb gefixed](https://github.com/locator-kn/locator-app/commit/6ef429859a4ba6cf2d1cbe9694fd6b8de3785e64) :P Warum das jetzt nur im Quelltext auftaucht und nicht auf der Seite angezeigt wird, bin ich jetzt zu faul das rauszusuchen :)

**Comment by timoweiss** [comment]
@mozzbozz war wahrscheinlich noch nicht deployed auf dem server. Ist nun auf jeden fall online :)
http://project.locator-app.com/impressum.html

**Comment by timoweiss** [comment]
PS: Ist kein entgültiges Impressum. Das muss nach wie vor von jemanden erstellt werden.
